name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to Hugging Face Hub
        uses: noplanman/huggingface-sync-action@v1
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Hemang18/AI-Interview-Bot
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
