[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
base="dark"
primaryColor="#10a37f"
backgroundColor="#212121"
secondaryBackgroundColor="#171717"
textColor="#ececf1"
font="sans serif"
